### ISSUE TITLE
Project Lombok

### ISSUE THREAD

**Issue by chriscn** [Drawethree/spigot-hibernate-demo#3]
Take a look at [Project Lombok](https://projectlombok.org/features/) can reduce a lot of the boilerplate in the classes.

**Comment by Drawethree** [comment]
Hi, the main reasons I am not that much fan of it:

Lombok can hide the implementation details: One of the main drawbacks of using Lombok is that it can make the code more difficult to understand, especially for developers who are not familiar with the library. Lombok's annotations can make it harder to see what code is actually being generated, which can make debugging and troubleshooting more challenging.

Lombok can lead to code bloat: Although Lombok can help reduce boilerplate code, it can also lead to code bloat if not used carefully. For example, if you use Lombok to generate too many methods or if you use Lombok annotations in too many places, your code may become bloated and harder to maintain.

Lombok may not be compatible with all development tools: Another potential issue with Lombok is that it may not be fully compatible with all development tools, especially older or less common tools. This can make it harder to use Lombok in some development environments, which can slow down development and create compatibility issues.

Lombok can introduce hidden errors: Because Lombok generates code at compile time, it can introduce hidden errors that may not be immediately obvious to developers. These errors can be hard to debug and can make it difficult to identify and fix issues in the code.
